<?php
/**
 * @category    Fedobe
 * @package     Fedobe_Landingpage
 */
?>
<?php if ($splashPage = $this->getSplashPage()): ?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php if ($this->isContentMode()): ?>
        <?php echo $this->getCmsBlockHtml() ?>
    <?php elseif ($this->isMixedMode()): ?>
        <?php echo $this->getCmsBlockHtml() ?>
        <?php echo $this->getProductListHtml() ?>
    <?php else: ?>
        <?php echo $this->getProductListHtml() ?>
    <?php endif; ?>
    <?php if ($description = $splashPage->getDescription()): ?>
        <!--div class="splash-description-full std"><?php echo $description ?></div-->
    <?php endif; ?>
<?php endif; ?>
<script type="text/javascript">
    jQuery(document).ready(function ($) {
        //$("div.checkbox_wrapper").click(function(){
        $(".clickhyperlink").click(function(){
            $(this).parent().trigger('click');
        });
    });
</script> 