<?php
if ($this->isActivePopUp()):
    ?>
    <script type="text/javascript">
    <?php if (is_numeric($this->getCookieLifeTime())): ?>
            EsNewsSubscribers.setCookieLiveTime(<?php echo $this->getCookieLifeTime(); ?>);
    <?php endif; ?>
    <?php if ($this->getCookieName()): ?>
            EsNewsSubscribers.setCookieName('<?php echo $this->getCookieName(); ?>');
    <?php endif; ?>
        EsNewsSubscribers.setBaseUrl('<?php echo $this->getBaseUrl(); ?>');
        
    </script>
    <div id="esns_background_layer" class="background_news_cls">

        <?php if ($this->getTheme() == 'default'): ?>
            <div id="esns_box_layer">
                <div id="esns_box_close"></div>
                <div id="esns_box_title">
                    <?php if ($this->getFirstTitle()): ?>
                        <div id="esns_box_block_1">
                            <?php echo $this->getFirstTitle() ?>
                        </div>
                    <?php endif; ?>
                    <?php if ($this->getSecondTitle()): ?>
                        <div id="esns_box_block_2">
                            <?php echo $this->getSecondTitle() ?>
                        </div>
                    <?php endif; ?>
                </div>

                <?php if ($this->getText()): ?>
                    <div class="esns_box_lines"></div>
                    <div id="esns_box_block_3">
                        <?php echo $this->getText() ?>
                    </div>
                <?php endif; ?>
                <div class="esns_box_lines"></div>
                <div id="esns_box_subscribe">
                    <div id="esns_box_subscribe_response_error"></div>
                    <div id="esns_box_subscribe_response_success"></div>
                    <div id="esns_box_subscribe_form">
                        <div id="esns_box_subscribe_input"><input onclick="if (this.value == '<?php echo $this->__('Email'); ?>')
                                            this.value = ''" onblur="if (this.value == '')
                                                        this.value = '<?php echo $this->__('Email'); ?>'" id="esns_email" name="subscribe_email" value="<?php echo $this->__('Your Email Id'); ?>" type="text"></div>
                        <div id="esns_box_subscribe_submit"><a href="javascript:void(0)" id="esns_submit" ><?php echo $this->__('Subscribe'); ?></a></div>
                    </div>
                </div>
            </div>
    
    <!--Start Of Fedobe Newsletter Theme   -->

<?php elseif ($this->getTheme() == 'fedobe'): ?>
    <div id="esns_box_layer" class="news_con">
            <span class="border-image"></span>
        <div class="news_main_conatiner clearer">
            <p> subscribe & win</p>
            <span><?php echo $this->getText() ?></span>
                <div id="esns_box_subscribe" class="news_form">
                    <div id="esns_box_subscribe_response_error"></div>
                    <div id="esns_box_subscribe_response_success"></div>
                    <div id="esns_box_subscribe_form">
                        <div id="esns_box_subscribe_input">
                        <input onclick="if (this.value == '<?php echo $this->__('Email'); ?>')
                                                    this.value = ''" onblur="if (this.value == '')
                                                                this.value = '<?php echo $this->__('Your email here....'); ?>'" id="esns_email" name="subscribe_email" value="<?php echo $this->__('Your Email Id'); ?>" type="text" class="email-input"></div>

                            <div id="esns_box_subscribe_submit" class="submit-button"><a href="javascript:void(0)" id="esns_submit" ><?php echo $this->__('Subscribe'); ?></a></div>
                <div id="esns_box_close"> No Thanks</div>
                        </div>
                    </div>
                </div>
                <span class="border-image"></span>
            </div>
        <?php endif; ?>

        <!--End Of Fedobe Newsletter Theme   -->
    </div>
<?php endif; ?>  