<?php  
 $colo =Mage::getStoreConfig('color_options/color/color-value');
if($colo) {  
//$color = "#".$colo;
   $color = $colo;
   //echo  $color;
     //echo "<script>alert('". $color. "');</script>";
$colo=  explode('#', $color);       
   //echo $enable;
   //echo "<br>";
   //echo $color;
   //if ($enable==1){
//Finding RGB Value // 
$R = substr($colo[1],0,2);
$G = substr($colo[1],2,2);
$B = substr($colo[1],4,2);

$R = hexdec($R);
$G = hexdec($G);
$B = hexdec($B);
//for $first_variation #2e8ab8 calculation start here//
        $r1=$R-5;
        $g1=$G-15;
        $b1=$B-20;
        if($r1<0)
        {
            $r1=-1*$r1;
        }
        if($g1<0)
        {
            $g1=-1*$g1;
        }
        if($b1<0)
        {
            $b1=-1*$b1;
        }
        $R1=dechex($r1);
	 If (strlen($R1)<2)
	 $R1='0'.$R1;
	 
	 $G1=dechex($g1);
	 If (strlen($G1)<2)
	 $G1='0'.$G1;
	 
	 $B1=dechex($b1);
	 If (strlen($B1)<2)
	 $B1='0'.$B1;
         $first_variation="#".$R1.$G1.$B1;
         //echo $first_variation;
         //echo "<br>";
 //$first_variation End Here//
//for $second_variation #246b8f calculation start here//
        $r2=$R-15;
        $g2=$G-46;
        $b2=$B-61;
        if($r2<0)
        {
            $r2=0;
        }
        if($g2<0)
        {
            $g2=0;
        }
        if($b2<0)
        {
            $b2=0;
        }
        $R2=dechex($r2);
	 If (strlen($R2)<2)
	 $R2='0'.$R2;
	 
	 $G2=dechex($g2);
	 If (strlen($G2)<2)
	 $G2='0'.$G2;
	 
	 $B2=dechex($b2);
	 If (strlen($B2)<2)
	 $B2='0'.$B2;
         $second_variation="#".$R2.$G2.$B2;
         //echo $second_variation;
         //echo "<br>";
 //$second_variation End Here//
//for $third_variation #297aa3 calculation start here//
        $r3=$R-10;
        $g3=$G-31;
        $b3=$B-41;
        if($r3<0)
        {
            $r3=0;
        }
        if($g3<0)
        {
            $g3=0;
        }
        if($b3<0)
        {
            $b3=0;
        }
        $R3=dechex($r3);
	 If (strlen($R3)<2)
	 $R3='0'.$R3;
	 
	 $G3=dechex($g3);
	 If (strlen($G3)<2)
	 $G3='0'.$G3;
	 
	 $B3=dechex($b3);
	 If (strlen($B3)<2)
	 $B3='0'.$B3;
         $third_variation="#".$R3.$G3.$B3;
         //echo $third_variation;
         //echo "<br>";
 //$third_variation End Here//
  
//for $fourth_variation #143d52 calculation start here//
        $r4=$R-31;
        $g4=$G-92;
        $b4=$B-122;
        if($r4<0)
        {
            $r4=0;
        }
        if($g4<0)
        {
            $g4=0;
        }
        if($b4<0)
        {
            $b4=0;
        }
        $R4=dechex($r4);
	 If (strlen($R4)<2)
	 $R4='0'.$R4;
	 
	 $G4=dechex($g4);
	 If (strlen($G4)<2)
	 $G4='0'.$G4;
	 
	 $B4=dechex($b4);
	 If (strlen($B4)<2)
	 $B4='0'.$B4;
         $fourth_variation="#".$R4.$G4.$B4;
         //echo $fourth_variation;
         //echo "<br>";
 //$fourth_variation End Here//   
//for $fiveth_variation #50a4cf calculation start here//
        $r5=$R+29;
        $g5=$G+11;
        $b5=$B+3;
        if($r5<0)
        {
            $r5=0;
        }
        if($g5<0)
        {
            $g5=0;
        }
        if($b5<0)
        {
            $b5=0;
        }
        $R5=dechex($r5);
	 If (strlen($R5)<2)
	 $R5='0'.$R5;
	 
	 $G5=dechex($g5);
	 If (strlen($G5)<2)
	 $G5='0'.$G5;
	 
	 $B5=dechex($b5);
	 If (strlen($B5)<2)
	 $B5='0'.$B5;
         $fiveth_variation="#".$R5.$G5.$B5;
        // echo $fiveth_variation;
         //echo "<br>";
 //$fiveth_variation End Here// 
?>
<style>
	
       
a {
  color: <?php echo $color ;?>;
  text-decoration: none;
}
h1, .h1 {
  margin: 0;
  margin-bottom: 0.7em;
  color: <?php echo $color ;?> ;
  font-family: "Raleway", "Helvetica Neue", Verdana, Arial, sans-serif;
  font-size: 28px;
  font-weight: 400;
  font-style: normal;
  line-height: 1.2;
  text-rendering: optimizeLegibility;
  text-transform: uppercase;
}
.block-title h2,
.block-title h3,
.block-title strong {
  margin: 0;
  margin-bottom: 10px;
  color: #636363;
  font-family: "Raleway", "Helvetica Neue", Verdana, Arial, sans-serif;
  font-size: 14px;
  font-weight: bold;
  font-style: normal;
  line-height: 1.4;
  text-rendering: optimizeSpeed;
  text-transform: uppercase;
  color:<?php echo $color ;?> ;
  margin-bottom: 0;
  text-transform: uppercase;
  font-weight: 600;
}
 .sidebar .block:not(.block-layered-nav) .block-title > strong:after {
    content: '';
    position: absolute;
    width: 0;
    height: 0;
    display: block;
    border-top: 4px solid transparent;
    border-bottom: 4px solid transparent;
    border-left: 4px solid <?php echo $color ;?> ;
    border-right: none;
    left: 10px;
    top: 50%;
    margin-top: -3px;
  }
  .sidebar .block:not(.block-layered-nav) .block-title.active > strong:after {
    content: '';
    position: absolute;
    width: 0;
    height: 0;
    display: block;
    border-right: 4px solid transparent;
    border-left: 4px solid transparent;
    border-top: 4px solid <?php echo $color ;?> ;
    border-bottom: none;
    left: 10px;
    top: 50%;
    margin-top: -3px;
  }
  .block-account li strong,
.block-cms-menu li strong {
  font-weight: 400;
  color: <?php echo $color ;?> ;
}
.block-account li a:hover,
.block-cms-menu li a:hover {
  color: <?php echo $color ;?> ;
}
.button,
.cart-table .product-cart-actions .button,
#co-shipping-method-form .buttons-set .button,
.footer .button {
  background: <?php echo $color ;?> ;
  display: inline-block;
  padding: 7px 15px;
  border: 0;
  color: #FFFFFF;
  font-size: 13px;
  font-weight: normal;
  font-family: "Raleway", "Helvetica Neue", Verdana, Arial, sans-serif;
  line-height: 19px;
  text-align: center;
  text-transform: uppercase;
  vertical-align: middle;
  white-space: nowrap;
}
.button2 span,
.button2 span span {
  line-height: 30px;
  height: 30px;
  text-decoration: underline;
  text-transform: uppercase;
  display: inline-block;
  color: <?php echo $color ;?> ;
  font-family: "Raleway", "Helvetica Neue", Verdana, Arial, sans-serif;
}
.breadcrumbs a:hover {
  color:<?php echo $color ;?> ;
}
.btn-previous:hover {
  background-color:<?php echo $color ;?>;
  border-color:<?php echo $color ;?>;
}
.btn-remove:after {
  content: 'X';
  color:<?php echo $color ;?>;
  height: 20px;
  line-height: 20px;
  width: 100%;
  font-size: 10px;
  font-family: Arial, "Helvetica Neue", Verdana, Arial, sans-serif;
  font-weight: bold;
}
.btn-previous:after {
  content: '';
  position: absolute;
  width: 0;
  height: 0;
  display: block;
  border-top: 4px solid transparent;
  border-bottom: 4px solid transparent;
  border-right: 4px solid <?php echo $color ;?>;
  border-left: none;
  position: absolute;
  top: 50%;
  left: 50%;
  margin-left: -2px;
  margin-top: -4px;
}
.promo-msg {
  color:<?php echo $color ;?>;
  text-align: center;
  margin: 10px;
  text-transform: uppercase;
  font-family: "Raleway", "Helvetica Neue", Verdana, Arial, sans-serif;
}
.price-box .price {
  color:<?php echo $color ;?>;
  font-size: 16px;
}
.price-box .minimal-price-link {
  padding-left: 1em;
  color:<?php echo $color ;?>;
  display: block;
  /* We want this to show on its own line, otherwise the layout looks funky */
}
.price-box .special-price {
  color:<?php echo $color ;?>;
  padding-left: 1em;
}
.truncated .truncated_full_value .item-options {
  display: none;
  position: absolute;
  z-index: 300;
  width: 200px;
  padding: 8px;
  border: 1px solid <?php echo $color ;?>;
  background-color: #F6F6F6;
  top: 21px;
  left: -100px;
}
.truncated .truncated_full_value .item-options:after {
  content: '';
  position: absolute;
  width: 0;
  height: 0;
  display: block;
  border-right: 7px solid transparent;
  border-left: 7px solid transparent;
  border-bottom: 7px solid <?php echo $color ;?>;
  border-top: none;
  left: 97px;
  top: -7px;
}
.no-touch .product-image:hover {
  border-color: <?php echo $color ;?>;
}
.pages a,
.pages .current {
  display: inline-block;
  border: 0;
  font-size: 13px;
  text-align: center;
  text-transform: uppercase;
  vertical-align: middle;
  white-space: nowrap;
  line-height: 30px;
  width: 25px;
  height: 30px;
  padding: 0;
  color: <?php echo $color ;?>;
  font-family: "Helvetica Neue", Verdana, Arial, sans-serif;
}
.pages .next:hover,
.pages .previous:hover {
  border: 1px solid <?php echo $color ;?>;
}
.pages .next:before {
  content: '';
  position: absolute;
  width: 0;
  height: 0;
  display: block;
  border-top: 4px solid transparent;
  border-bottom: 4px solid transparent;
  border-left: 4px solid <?php echo $color ;?>;
  border-right: none;
  top: 50%;
  margin-top: -3px;
  left: 50%;
  margin-left: -2px;
}
.pages .previous:before {
  content: '';
  position: absolute;
  width: 0;
  height: 0;
  display: block;
  border-top: 4px solid transparent;
  border-bottom: 4px solid transparent;
  border-right: 4px solid <?php echo $color ;?>;
  border-left: none;
  top: 50%;
  margin-top: -3px;
  left: 50%;
  margin-left: -2px;
}
#checkout-review-table .summary-collapse:before,
#shopping-cart-totals-table .summary-collapse:before,
body.customer-account .data-table .summary-collapse:before {
  content: '';
  position: absolute;
  width: 0;
  height: 0;
  display: block;
  border-right: 7px solid transparent;
  border-left: 7px solid transparent;
  border-top: 7px solid <?php echo $color ;?>;
  border-bottom: none;
  position: static;
  display: inline-block;
  margin-right: 5px;
}
#checkout-review-table .show-details .summary-collapse:before,
#shopping-cart-totals-table .show-details .summary-collapse:before,
body.customer-account .data-table .show-details .summary-collapse:before {
  content: '';
  position: absolute;
  width: 0;
  height: 0;
  display: block;
  border-right: 7px solid transparent;
  border-left: 7px solid transparent;
  border-bottom: 7px solid <?php echo $color ;?>;
  border-top: none;
  position: static;
  display: inline-block;
  margin-right: 5px;
}
.input-text:focus {
	outline-color : <?php echo $color ;?>;
  border: 1px solid <?php echo $color ;?>;
}
.input-text.validation-failed {
  border-color:<?php echo $color ;?>;
}

.input-text.validation-failed:focus {
  outline-color: <?php echo $color ;?>;
}
.header-language-background {
  padding: 10px;
  background-color: <?php echo $color ;?>;
  text-transform: uppercase;
}
.nav-primary li.menu-active > a,
  .nav-primary li.sub-menu-active > a {
    color: <?php echo $color ;?>;
  }
  .nav-primary a:hover,
  .nav-primary li:hover > a {
    color:<?php echo $color ;?>;
  }
   #header-account a:hover {
    color:<?php echo $color ;?>;
  }
  #header-account a:hover {
  color: <?php echo $color ;?>;
}
@media only screen and (min-width: 771px) {
  .skip-cart {
    color: <?php echo $color ;?>;
    text-transform: uppercase;
  }
.skip-cart .count,
  .skip-link.skip-active .count {
    color:<?php echo $color ;?>;
  }
}
.footer .block-title,
.footer address {
  color:<?php echo $color ;?>;
}
.footer .links a:hover {
  color:<?php echo $color ;?>;
}
h2.product-name a:hover,
h3.product-name a:hover,
h4.product-name a:hover,
h5.product-name a:hover,
p.product-name a:hover {
  color:<?php echo $color ;?>;
  text-decoration: none;
}
.block-layered-nav .block-subtitle--filter:after {
  content: '';
  position: absolute;
  width: 0;
  height: 0;
  display: block;
  border-right: 4px solid transparent;
  border-left: 4px solid transparent;
  border-top: 4px solid <?php echo $color ;?>;
  border-bottom: none;
  left: 10px;
  top: 50%;
  margin-top: -3px;
}
.block-layered-nav .block-content > dl > dt:after {
  content: '';
  position: absolute;
  width: 0;
  height: 0;
  display: block;
  border-right: 4px solid transparent;
  border-left: 4px solid transparent;
  border-top: 4px solid <?php echo $color ;?>;
  border-bottom: none;
  left: 10px;
  top: 50%;
  margin-top: -3px;
}
@media only screen and (min-width: 771px) {
.block-layered-nav .block-content > dl > dt:hover {
    color: <?php echo $color ;?>;
  }
  .block-layered-nav .block-content > dl > dt:after {
    content: '';
    position: absolute;
    width: 0;
    height: 0;
    display: block;
    border-top: 4px solid transparent;
    border-bottom: 4px solid transparent;
    border-left: 4px solid <?php echo $color ;?>;
    border-right: none;
  }
  .block-layered-nav .block-content.accordion-open > dl > dt.current:after {
    content: '';
    position: absolute;
    width: 0;
    height: 0;
    display: block;
    border-right: 4px solid transparent;
    border-left: 4px solid transparent;
    border-top: 4px solid <?php echo $color ;?>;
    border-bottom: none;
    left: 6px;
    top: 50%;
    margin-top: -3px;
  }
  .block-layered-nav .block-subtitle--filter {
    background-color:<?php echo $color ;?>;
    border: 0;
    margin-bottom: 0;
    display: block;
    color: #FFFFFF;
  }
}
.product-view .product-shop .product-name .h1,
.product-view .product-img-box .product-name h1 {
  color: <?php echo $color ;?>;
  margin-bottom: 10px;
  border: 0;
}
.product-view .product-shop .price-box .regular-price .price,
.product-view .product-shop .price-box .special-price .price,
.product-view .product-shop .price-box .full-product-price .price {
  color: <?php echo $color ;?>;
  font-size: 24px;
}
.product-collateral .toggle-tabs li.current span,
  .product-collateral .toggle-tabs li:hover span {
    color: <?php echo $color ;?>;
  }
  .product-collateral > dl > dt:after {
    content: '';
    position: absolute;
    width: 0;
    height: 0;
    display: block;
    border-right: 4px solid transparent;
    border-left: 4px solid transparent;
    border-top: 4px solid <?php echo $color ;?>;
    border-bottom: none;
    left: 10px;
    top: 50%;
    margin-top: -3px;
  }
  .product-collateral > dl > dt:hover {
    color: <?php echo $color ;?>;
  }
  .product-collateral > dl > dt:after {
    content: '';
    position: absolute;
    width: 0;
    height: 0;
    display: block;
    border-top: 4px solid transparent;
    border-bottom: 4px solid transparent;
    border-left: 4px solid <?php echo $color ;?>;
    border-right: none;
  }
  .product-collateral.accordion-open > dl > dt.current:after {
    content: '';
    position: absolute;
    width: 0;
    height: 0;
    display: block;
    border-right: 4px solid transparent;
    border-left: 4px solid transparent;
    border-top: 4px solid <?php echo $color ;?>;
    border-bottom: none;
    left: 6px;
    top: 50%;
    margin-top: -3px;
  }
  .grouped-items-table .name-wrapper {
  color: <?php echo $color ;?>;
  font-family: "Raleway", "Helvetica Neue", Verdana, Arial, sans-serif;
}
.cart-table .cart-tax-total:after {
  content: '';
  position: absolute;
  width: 0;
  height: 0;
  display: block;
  border-top: 6px solid transparent;
  border-bottom: 6px solid transparent;
  border-right: 6px solid <?php echo $color ;?>;
  border-left: none;
  position: absolute;
  top: 3px;
  right: -11px;
}
.cart-table .cart-tax-total.cart-tax-total-expanded:after {
  content: '';
  position: absolute;
  width: 0;
  height: 0;
  display: block;
  border-right: 6px solid transparent;
  border-left: 6px solid transparent;
  border-top: 6px solid <?php echo $color ;?>;
  border-bottom: none;
  right: -15px;
  top: 6px;
}
.crosssell h2 {
  color:<?php echo $color ;?>;
}
.opc .section .step-title .number,
.opc .section.allow.active .step-title .number,
.no-touch .opc .section.allow:hover .step-title .number {
  width: 26px;
  height: 26px;
  text-align: center;
  color: #FFFFFF;
  line-height: 26px;
  background-color: <?php echo $color ;?>;
  display: block;
  position: absolute;
  top: 50%;
  left: 10px;
  margin-top: -13px;
}
.opc .section.allow .step-title:hover h2,
.opc .section.active .step-title h2 {
  color: <?php echo $color ;?>;
}
#narrow-by-list dd .swatch-link:hover .swatch-label {
  border-color: <?php echo $color ;?>;
}
.configurable-swatch-list .hover .swatch-link,
.configurable-swatch-list .selected .swatch-link,
.swatch-link:hover {
  border-color: <?php echo $color ;?>;
}
.product-view .product-options .swatch-attr .select-label {
  display: inline;
  font-weight: normal;
  color: <?php echo $color ;?>;
  padding-left: 5px;
}
#customer-reviews h2 {
  color: <?php echo $color ;?>;
  font-size: 12px;
  text-transform: uppercase;
}
#customer-reviews h3 span {
  color: <?php echo $color ;?>;
}
#customer-reviews dl dd .review-meta {
  color: <?php echo $color ;?>;
  font-family: "Raleway", "Helvetica Neue", Verdana, Arial, sans-serif;
  font-size: 10px;
  font-weight: normal;
  text-transform: uppercase;
}
#wishlist-table .product-name a {
  color:<?php echo $color ;?>;
}
#wishlist-table textarea:focus {
  border: 1px solid <?php echo $color ;?>;
}
#wishlist-table .giftregisty-add li {
  cursor: pointer;
  color: <?php echo $color ;?>;
  margin-bottom: 3px;
}
#wishlist-table .truncated .details {
  background: none;
  color: <?php echo $color ;?>;
}
.header-minicart .product-details .product-name a {
  color:<?php echo $color ;?>;
}
.header-minicart .info-wrapper td {
  color: <?php echo $color ;?>;
  clear: right;
}
.header-minicart .subtotal .price {
  color: <?php echo $color ;?>;
}
.search-autocomplete ul {
  -webkit-border-radius: 2px;
  -moz-border-radius: 2px;
  -ms-border-radius: 2px;
  -o-border-radius: 2px;
  border-radius: 2px;
  background-color: #FFFFFF;
  border: 1px solid <?php echo $color ;?>;
  left: 0;
  padding-left: 0;
  position: absolute;
  top: 0;
  width: 100%;
}
.search-autocomplete ul li {
  border-bottom: 1px solid #f4f4f4;
  color: <?php echo $color ;?>;
  cursor: pointer;
  font-size: 12px;
  padding: 4px 6px;
  text-align: left;
}
.search-autocomplete ul li.selected {
  background-color: <?php echo $color ;?>;
  color: white;
}
.search-autocomplete:before {
  content: '';
  position: absolute;
  width: 0;
  height: 0;
  display: block;
  border-right: 7px solid transparent;
  border-left: 7px solid transparent;
  border-bottom: 7px solid <?php echo $color ;?>;
  border-top: none;
  left: 50%;
  top: -7px;
}
.product-review .product-details h2 {
  border-bottom: 1px solid #cccccc;
  color: <?php echo $color ;?>;
  font-size: 16px;
  font-weight: 600;
  font-family: "Raleway", "Helvetica Neue", Verdana, Arial, sans-serif;
  padding-bottom: 10px;
}
.cms-no-route .std h1 {
  color:<?php echo $color ;?>;
}
.cms-page-view .std h2,
.cms-no-route .std h2 {
  color:<?php echo $color ;?>;
}
#accordion > dl > dt:after {
  content: '';
  position: absolute;
  width: 0;
  height: 0;
  display: block;
  border-right: 4px solid transparent;
  border-left: 4px solid transparent;
  border-top: 4px solid <?php echo $color ;?>;
  border-bottom: none;
  left: 10px;
  top: 50%;
  margin-top: -3px;
}
a:hover {
  color: <?php echo $first_variation ;?>;
  text-decoration: underline;
}
.button:hover,
.cart-table .product-cart-actions .button:hover,
#co-shipping-method-form .buttons-set .button:hover,
.footer .button:hover {
  background: <?php echo $first_variation ;?>;
  cursor: pointer;
}
.block-layered-nav .block-subtitle--filter:hover {
    background-color: <?php echo $first_variation ;?>;
    color: #FFFFFF;
  }
  .slideshow-pager span:hover:before {
  background-color: <?php echo $first_variation ;?>;
}
.slideshow-prev:hover:before {
  border-color: transparent <?php echo $first_variation ;?> transparent transparent;
}
.slideshow-next:hover:before {
  border-color: transparent transparent transparent <?php echo $first_variation ;?>;
}
.search-autocomplete ul li:hover {
  color: <?php echo $first_variation ;?>;
}
.button2 span:hover,
.button2 span span:hover {
  text-decoration: none;
  color: <?php echo $second_variation ;?>;
}
.pages .next:hover:before {
  content: '';
  position: absolute;
  width: 0;
  height: 0;
  display: block;
  border-top: 4px solid transparent;
  border-bottom: 4px solid transparent;
  border-left: 4px solid <?php echo $second_variation ;?>;
  border-right: none;
}
.pages .previous:hover:before {
  content: '';
  position: absolute;
  width: 0;
  height: 0;
  display: block;
  border-top: 4px solid transparent;
  border-bottom: 4px solid transparent;
  border-right: 4px solid <?php echo $second_variation ;?>;
  border-left: none;
}
#checkout-review-table .summary-collapse:hover:before,
#shopping-cart-totals-table .summary-collapse:hover:before,
body.customer-account .data-table .summary-collapse:hover:before {
  content: '';
  position: absolute;
  width: 0;
  height: 0;
  display: block;
  border-right: 7px solid transparent;
  border-left: 7px solid transparent;
  border-top: 7px solid <?php echo $second_variation ;?>;
  border-bottom: none;
  position: static;
  display: inline-block;
  margin-right: 5px;
}
#checkout-review-table .show-details .summary-collapse:hover:before,
#shopping-cart-totals-table .show-details .summary-collapse:hover:before,
body.customer-account .data-table .show-details .summary-collapse:hover:before {
  content: '';
  position: absolute;
  width: 0;
  height: 0;
  display: block;
  border-right: 7px solid transparent;
  border-left: 7px solid transparent;
  border-bottom: 7px solid <?php echo $second_variation ;?>;
  border-top: none;
  position: static;
  display: inline-block;
  margin-right: 5px;
}
.slideshow-pager span.cycle-pager-active:before {
  background-color: <?php echo $third_variation ;?>;
}
.button:focus,
.cart-table .product-cart-actions .button:focus,
#co-shipping-method-form .buttons-set .button:focus,
.footer .button:focus {
  background-color:  <?php echo $third_variation ;?>;
  outline: none;
  color: #FFFFFF;
}
.button:active,
.cart-table .product-cart-actions .button:active,
#co-shipping-method-form .buttons-set .button:active,
.footer .button:active {
  background: <?php echo $third_variation ;?>;
  color: #FFFFFF;
}
a:focus {
  outline-color: #3091c2;
  color: <?php echo $fourth_variation ;?>;
}
.header-minicart .block-subtitle {
  color: <?php echo $fiveth_variation ;?>;
  font-family: "Raleway", "Helvetica Neue", Verdana, Arial, sans-serif;
  font-size: 10px;
  font-weight: bold;
  line-height: 1.4;
  padding: 5px;
  text-align: center;
  text-transform: uppercase;
  margin-bottom: 0px;
}
</style>
<?php
}
else echo "No color Selected";
?>




