<?php

$installer = $this;

$installer->startSetup();

$installer->run("
    DROP TABLE IF EXISTS fedobe_global_settings;
    CREATE TABLE fedobe_global_settings (
            `style_id` int(11) unsigned NOT NULL auto_increment,
            `style_name` varchar(255) NOT NULL,
            PRIMARY KEY (`style_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    INSERT INTO fedobe_global_settings VALUES(1,'Classic'), (2,'Urban'), (3,'Trendy');
    CREATE TABLE IF NOT EXISTS fedobe_module_unique_name (
            `module_id` int(11) unsigned NOT NULL auto_increment,
            `module_name` varchar(255) NOT NULL,
            PRIMARY KEY (`module_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    CREATE TABLE IF NOT EXISTS fedobe_design_attribute_name (
            `attribute_name_id` int(11) unsigned NOT NULL auto_increment,
            `module_id` int(11) unsigned NOT NULL,
            `style_id` int(11) unsigned NOT NULL,
            `attribute_name` varchar(255) NOT NULL, 
            PRIMARY KEY (`attribute_name_id`),
            FOREIGN KEY(`module_id`) REFERENCES fedobe_module_unique_name (`module_id`),
            FOREIGN KEY(`style_id`) REFERENCES fedobe_global_settings (`style_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    CREATE TABLE IF NOT EXISTS fedobe_design_attribute_value (
            `attribute_value_id` int(11) unsigned NOT NULL auto_increment,
            `attribute_name_id` int(11) unsigned NOT NULL,
            `attribute_value` varchar(255) NOT NULL, 
            PRIMARY KEY (`attribute_value_id`),
            FOREIGN KEY(`attribute_name_id`) REFERENCES fedobe_design_attribute_name (`attribute_name_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    

INSERT INTO {$this->getTable('fedobe_module_unique_name')} VALUES ('','product-carousel');


INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'border_width' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Classic';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'border_type' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Classic';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'border_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Classic';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'text_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Classic';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'link_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Classic';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'link_hover_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Classic';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'price_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Classic';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'new_price_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Classic';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'text_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Classic';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'button_background_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Classic';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'button_text_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Classic';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'button_hover_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Classic';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'button_hover_text_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Classic';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'product_label_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Classic';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'product_label_bg_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Classic';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'discount_percentage_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Classic';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'discount_percentage_bg' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Classic';

INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'border_width' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Urban';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'border_type' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Urban';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'border_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Urban';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'text_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Urban';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'link_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Urban';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'link_hover_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Urban';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'price_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Urban';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'new_price_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Urban';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'text_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Urban';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'button_background_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Urban';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'button_text_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Urban';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'button_hover_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Urban';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'button_hover_text_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Urban';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'product_label_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Urban';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'product_label_bg_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Urban';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'discount_percentage_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Urban';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'discount_percentage_bg' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Urban';

INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'border_width' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Trendy';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'border_type' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Trendy';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'border_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Trendy';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'text_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Trendy';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'link_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Trendy';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'link_hover_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Trendy';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'price_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Trendy';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'new_price_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Trendy';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'text_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Trendy';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'button_background_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Trendy';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'button_text_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Trendy';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'button_hover_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Trendy';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'button_hover_text_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Trendy';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'product_label_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Trendy';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'product_label_bg_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Trendy';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'discount_percentage_color' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Trendy';
INSERT INTO {$this->getTable('fedobe_design_attribute_name')} SELECT NULL, module_unique_name.module_id, global_style_name.style_id, 'discount_percentage_bg' FROM fedobe_module_unique_name as module_unique_name, fedobe_global_settings as global_style_name WHERE module_unique_name.module_name = 'product-carousel' AND global_style_name.style_name = 'Trendy';

    






INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '1px' FROM fedobe_design_attribute_name WHERE attribute_name = 'border_width' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Classic');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, 'solid' FROM fedobe_design_attribute_name WHERE attribute_name = 'border_type' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Classic');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#D3D3D3' FROM fedobe_design_attribute_name WHERE attribute_name = 'border_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Classic');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FFFFFF' FROM fedobe_design_attribute_name WHERE attribute_name = 'text_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Classic');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#DDDDDD' FROM fedobe_design_attribute_name WHERE attribute_name = 'link_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Classic');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#EEEEEE' FROM fedobe_design_attribute_name WHERE attribute_name = 'link_hover_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Classic');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#A4C7FF' FROM fedobe_design_attribute_name WHERE attribute_name = 'price_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Classic');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FB0008' FROM fedobe_design_attribute_name WHERE attribute_name = 'new_price_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Classic');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FFFFFF' FROM fedobe_design_attribute_name WHERE attribute_name = 'text_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Classic');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FFC38F' FROM fedobe_design_attribute_name WHERE attribute_name = 'button_background_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Classic');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FFFFFF' FROM fedobe_design_attribute_name WHERE attribute_name = 'button_text_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Classic');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FF3E17' FROM fedobe_design_attribute_name WHERE attribute_name = 'button_hover_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Classic');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#250DFF' FROM fedobe_design_attribute_name WHERE attribute_name = 'button_hover_text_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Classic');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#F824FF' FROM fedobe_design_attribute_name WHERE attribute_name = 'product_label_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Classic');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FFF5FB' FROM fedobe_design_attribute_name WHERE attribute_name = 'product_label_bg_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Classic');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FFF5FB' FROM fedobe_design_attribute_name WHERE attribute_name = 'discount_percentage_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Classic');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FFF5FB' FROM fedobe_design_attribute_name WHERE attribute_name = 'discount_percentage_bg' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Classic');

INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '2' FROM fedobe_design_attribute_name WHERE attribute_name = 'border_width' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Urban');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, 'outset' FROM fedobe_design_attribute_name WHERE attribute_name = 'border_type' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Urban');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#000000' FROM fedobe_design_attribute_name WHERE attribute_name = 'border_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Urban');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FFFFFF' FROM fedobe_design_attribute_name WHERE attribute_name = 'text_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Urban');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#DDDDDD' FROM fedobe_design_attribute_name WHERE attribute_name = 'link_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Urban');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#EEEEEE' FROM fedobe_design_attribute_name WHERE attribute_name = 'link_hover_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Urban');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#A4C7FF' FROM fedobe_design_attribute_name WHERE attribute_name = 'price_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Urban');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FB0008' FROM fedobe_design_attribute_name WHERE attribute_name = 'new_price_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Urban');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FFFFFF' FROM fedobe_design_attribute_name WHERE attribute_name = 'text_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Urban');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FFC38F' FROM fedobe_design_attribute_name WHERE attribute_name = 'button_background_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Urban');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FFFFFF' FROM fedobe_design_attribute_name WHERE attribute_name = 'button_text_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Urban');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FF3E17' FROM fedobe_design_attribute_name WHERE attribute_name = 'button_hover_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Urban');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#250DFF' FROM fedobe_design_attribute_name WHERE attribute_name = 'button_hover_text_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Urban');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#F824FF' FROM fedobe_design_attribute_name WHERE attribute_name = 'product_label_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Urban');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FFF5FB' FROM fedobe_design_attribute_name WHERE attribute_name = 'product_label_bg_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Urban');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FFF5FB' FROM fedobe_design_attribute_name WHERE attribute_name = 'discount_percentage_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Urban');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FFF5FB' FROM fedobe_design_attribute_name WHERE attribute_name = 'discount_percentage_bg' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Urban');

INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '0' FROM fedobe_design_attribute_name WHERE attribute_name = 'border_width' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Trendy');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, 'dotted' FROM fedobe_design_attribute_name WHERE attribute_name = 'border_type' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Trendy');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#000FFF' FROM fedobe_design_attribute_name WHERE attribute_name = 'border_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Trendy');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FFFFFF' FROM fedobe_design_attribute_name WHERE attribute_name = 'text_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Trendy');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#DDDDDD' FROM fedobe_design_attribute_name WHERE attribute_name = 'link_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Trendy');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#EEEEEE' FROM fedobe_design_attribute_name WHERE attribute_name = 'link_hover_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Trendy');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#A4C7FF' FROM fedobe_design_attribute_name WHERE attribute_name = 'price_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Trendy');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FB0008' FROM fedobe_design_attribute_name WHERE attribute_name = 'new_price_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Trendy');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FFFFFF' FROM fedobe_design_attribute_name WHERE attribute_name = 'text_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Trendy');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FFC38F' FROM fedobe_design_attribute_name WHERE attribute_name = 'button_background_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Trendy');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FFFFFF' FROM fedobe_design_attribute_name WHERE attribute_name = 'button_text_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Trendy');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FF3E17' FROM fedobe_design_attribute_name WHERE attribute_name = 'button_hover_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Trendy');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#250DFF' FROM fedobe_design_attribute_name WHERE attribute_name = 'button_hover_text_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Trendy');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#F824FF' FROM fedobe_design_attribute_name WHERE attribute_name = 'product_label_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Trendy');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FFF5FB' FROM fedobe_design_attribute_name WHERE attribute_name = 'product_label_bg_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Trendy');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FFF5FB' FROM fedobe_design_attribute_name WHERE attribute_name = 'discount_percentage_color' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Trendy');
INSERT INTO {$this->getTable('fedobe_design_attribute_value')} SELECT NULL, attribute_name_id, '#FFF5FB' FROM fedobe_design_attribute_name WHERE attribute_name = 'discount_percentage_bg' AND module_id = (SELECT module_id FROM fedobe_module_unique_name WHERE module_name = 'product-carousel') AND style_id = (SELECT style_id FROM fedobe_global_settings WHERE style_name = 'Trendy');

");

$setup = new Mage_Eav_Model_Entity_Setup('core_setup');
$setup->addAttribute('catalog_product', 'fedobefeatured', array(
        'type'              => 'int',
        'backend_type'      => 'int',
        'backend'           => '',
        'frontend'          => '',
        'label'             => 'Is Featured Product',
        'input'             => 'boolean',
        'frontend_class'    => '',
        'source'            => 'eav/entity_attribute_source_boolean',
        'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
        'visible'           => false,
        'required'          => false,
        'user_defined'      => true,
        'default'           => '',
        'searchable'        => false,
        'filterable'        => false,
        'comparable'        => false,
        'visible_on_front'  => false,
        'unique'            => false,
        'apply_to'          => '',
        'is_configurable'   => false
));
$setup->addAttributeToSet('catalog_product', 'Default', 'General', 'fedobefeatured');

$installer->endSetup();

