<?php if (Mage::getStoreConfig('ajax_search/general/enabled')) :?>
<form id="search_mini_form" action="<?php echo $this->helper('catalogSearch')->getResultUrl() ?>" method="get">
     <fieldset>
        <legend><?php echo $this->__('Search Site') ?></legend>
        <div class="mini-search form-search clearer" id="search-content">
       	    <div id="searchajaxico" class=""></div>
            <input id="search" type="text" class="input-text" name="<?php echo $this->helper('catalogSearch')->getQueryParamName() ?>" placeholder="<?php echo Mage::getStoreConfig('ajax_search/general/searchfieldtext'); ?>" onblur="if(this.value=='')this.value='<?php echo Mage::getStoreConfig('ajax_search/general/searchfieldtext'); ?>';" onfocus="if(this.value=='<?php echo Mage::getStoreConfig('ajax_search/general/searchfieldtext'); ?>')this.value='';" />
            <button type="submit" title="<?php echo $this->__('Search') ?>" class="searchbutton"></button>
             <div id="loading" style="display: none;">
            
        </div>

            
        </div>
    </fieldset>
</form>
<script type="text/javascript">
//<![CDATA[
    <?php $_isSecure = $this->getRequest()->isSecure(); ?>
    function initAutocomplete(){
        new Autocomplete('search', { 
            serviceUrl   : '<?php echo $this->getUrl('ajaxsearch', array('_secure' => $_isSecure)); ?>',
            enableloader : <?php echo Mage::getStoreConfig('ajax_search/general/enableloader') ? 'true' : 'false'; ?>,
            minChars     : <?php echo Mage::getStoreConfig('ajax_search/general/minchars'); ?>, 
            maxHeight    : <?php echo Mage::getStoreConfig('ajax_search/general/maxheight'); ?>,
            width        : <?php echo Mage::getStoreConfig('ajax_search/general/width'); ?>,
            searchtext   : '<?php echo Mage::getStoreConfig('ajax_search/general/searchfieldtext'); ?>',
            onSelect     : function (value, data) {setLocation(value.url);}
        });
    }
    if (Prototype.Browser.IE) {
       Event.observe(window, 'load', initAutocomplete);
    } else {
       document.observe("dom:loaded", initAutocomplete);
    }
//]]>

</script>
<?php endif; ?>
