<?php
	Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
$up_arrow_img=$this->getSkinUrl('images/fedobe/notificationbar/up-arrow.png');
$down_arrow_img=$this->getSkinUrl('images/fedobe/notificationbar/down-arrow.png');
$today=Mage::getModel('core/date')->date('m/d/Y');
$today=explode("/",$today);
//echo $today[0];
 $display =Mage::getStoreConfig('design/notificationbar/display');
 $content =Mage::getStoreConfig('design/notificationbar/content');
 $start_date =Mage::getStoreConfig('design/notificationbar/start_date');
 $end_date =Mage::getStoreConfig('design/notificationbar/end_date');
 $bg_color =Mage::getStoreConfig('design/notificationbar/bg_color');
 $text_color =Mage::getStoreConfig('design/notificationbar/text_color');
 $text_fornt_size =Mage::getStoreConfig('design/notificationbar/text_fornt_size');
 
//echo "<br>Dispaly:$display";
//echo "<br>content:$content";
//echo "<br>start_date:$start_date";
//echo "<br>end_date:$end_date";
//echo "<br>bg_color:$bg_color";
//echo "<br>text_color:$text_color";
//echo "<br>text_fornt_size:$text_fornt_size";

if($display == 1)
{
	
?>
<!DOCTYPE html>
<html>
<head>
	<style type="text/css">
   .jquery-bar {
	background: <?php echo $bg_color;?>;
	color: <?php echo $text_color;?>;
	font-size:<?php echo $text_fornt_size;?>;
	width:101.40%;
	position: relative;	
	margin:5px 0px 0px -5px;
	padding: 2px 0px 0px 0px;	
	border-bottom:2px solid #CC0000;
	box-shadow: 0px 4px 5px #AAAAAA;
	font-family: 'Lato Regular', Arial;
	text-transform:uppercase;
	height: 39px;
	margin-top: 0px;
}

.jquery-bar .notification {
	display:block;
	width:auto;
}

.downbar {
	cursor:pointer;	
	top:0px;
	right:70px;	
	padding:0px 3px 0px 3px;
	position:absolute;
	background:#FFFFFF;
	border-radius:0px 0px 5px 5px;	
	border:2px solid #CC0000;
	box-shadow: 0px 4px 5px #AAAAAA;	
	border-top:none;
}

.downbar:hover{
	background: url(../jix/bg.png);
	cursor:pointer;
}

.down {
	position:absolute;
	top:3px;
	right:85px;
}

.up {
	top: -45px;
	display: none;
}

.arrow {
	cursor:pointer;
}

.font-style{
	text-align: center;
}

.font-style a{
	color:#CC0000;
	font-size:15px;
	text-decoration:underline;
	text-transform:none;
}
</style>


<script>

   jQuery(function($) {
        // jBar Script by Todd Motto
        $('.downbar').delay(1000).fadeIn(400).addClass('up');
        $('.jquery-bar').hide().delay(2500).slideDown(400);
        $('.jquery-arrow').click(function(){
            $('.downbar').toggleClass('up', 400);          
            $('.jquery-bar').slideToggle();
        });     
    });
</script>
</head>
<body>
<!-- Start jQuery Notification Bar -->
<div class="jquery-bar">
    <span class="notification">
    <?php
        if($content)
        {?>
        	<p class="font-style"><?php echo $content; ?></p> 
       <?php }else{ ?>
        <p class="font-style">&laquo; Back to -         
        <a href="http://store.fedobe.com/">Bumper Offer On Online Shopping</a>(Default Message)
        </p> 
        <?php } ?>
        <p class="jquery-arrow down"><img src="<?php echo $up_arrow_img; ?>" alt="Click to Hide Notification" style="cursor:pointer;"></p>
    </span>
</div>
<span class="downbar jquery-arrow"><img src="<?php echo $down_arrow_img; ?>" alt="Click to Show Notification" style="cursor:pointer;"></span>
<!-- End jQuery Notification Bar -->

</body>
</html>
<?php
}
?>